### PR TITLE
Adjust indentation and remove not valid comma

### PR DESCRIPTION
**Pull request by gregorwolf**

### CODE REVIEW

**Comment by OlMue** [comment]
Hi @gregorwolf, thanks for your contribution! We'll take a look and will get back to you.

@MHoltbruegge

**Comment by dominikschreiber** [comment]
cc @melaniedisson

**Review by melaniedisson — APPROVED** [review]

**Comment by melaniedisson** [comment]
Thank you @gregorwolf for your contribution. The change is available with the next documentation release on SAP Help Portal.

**Comment by gregorwolf** [comment]
My SAP Community User ID is 12545.

**Pull request merged**
